CITY = {'https://as.meituan.com': '鞍山', 'https://anqing.meituan.com': '安庆', 'https://ay.meituan.com': '安阳',
        'https://anshun.meituan.com': '安顺', 'https://ankang.meituan.com': '安康', 'https://aq.meituan.com': '安丘',
        'https://anyue.meituan.com': '安岳', 'https://anlushi.meituan.com': '安陆市', 'https://aks.meituan.com': '阿克苏',
        'https://anzhouqu.meituan.com': '安州区', 'https://atushishi.meituan.com': '阿图什市', 'https://aj.meituan.com': '安吉',
        'https://als.meituan.com': '阿拉善盟', 'https://arongqi.meituan.com': '阿荣旗', 'https://anping.meituan.com': '安平',
        'https://anxi.meituan.com': '安溪', 'https://anning.meituan.com': '安宁', 'https://anhua.meituan.com': '安化',
        'https://alaer.meituan.com': '阿拉尔', 'https://anfu.meituan.com': '安福', 'https://aletaishi.meituan.com': '阿勒泰市',
        'https://achengqu.meituan.com': '阿城区', 'https://am.meituan.com': '澳门', 'https://alt.meituan.com': '阿勒泰',
        'https://al.meituan.com': '阿里', 'https://ab.meituan.com': '阿坝', 'https://bj.meituan.com': '北京',
        'https://bt.meituan.com': '包头', 'https://bd.meituan.com': '保定', 'https://bengbu.meituan.com': '蚌埠',
        'https://bozhou.meituan.com': '亳州', 'https://bz.meituan.com': '滨州', 'https://baoji.meituan.com': '宝鸡',
        'https://bc.meituan.com': '白城', 'https://hbbazhou.meituan.com': '霸州', 'https://byne.meituan.com': '巴彦淖尔',
        'https://bh.meituan.com': '北海', 'https://baise.meituan.com': '百色', 'https://bazhong.meituan.com': '巴中',
        'https://bijie.meituan.com': '毕节', 'https://bs.meituan.com': '保山', 'https://benxi.meituan.com': '本溪',
        'https://by.meituan.com': '白银', 'https://baishan.meituan.com': '白山', 'https://bishan.meituan.com': '璧山',
        'https://baiquanxian.meituan.com': '拜泉县', 'https://baichengxian.meituan.com': '拜城县',
        'https://baoying.meituan.com': '宝应', 'https://beiliu.meituan.com': '北流', 'https://boai.meituan.com': '博爱',
        'https://bachuxian.meituan.com': '巴楚县', 'https://baofeng.meituan.com': '宝丰', 'https://boxing.meituan.com': '博兴',
        'https://biyang.meituan.com': '泌阳', 'https://binxian.meituan.com': '彬州市',
        'https://bayanxian.meituan.com': '巴彦县', 'https://boshan.meituan.com': '博山', 'https://binyang.meituan.com': '宾阳',
        'https://botou.meituan.com': '泊头市', 'https://boluoxian.meituan.com': '博罗县',
        'https://bobaixian.meituan.com': '博白县', 'https://beizhenshi.meituan.com': '北镇市',
        'https://beianshi.meituan.com': '北安市', 'https://binhai.meituan.com': '滨海', 'https://beipei.meituan.com': '北碚',
        'https://betl.meituan.com': '博尔塔拉', 'https://baz.meituan.com': '巴州', 'https://cq.meituan.com': '重庆',
        'https://cd.meituan.com': '成都', 'https://cz.meituan.com': '常州', 'https://cc.meituan.com': '长春',
        'https://chs.meituan.com': '长沙', 'https://cangzhou.meituan.com': '沧州', 'https://changzhi.meituan.com': '长治',
        'https://cixi.meituan.com': '慈溪', 'https://chuzhou.meituan.com': '滁州', 'https://changde.meituan.com': '常德',
        'https://chenzhou.meituan.com': '郴州', 'https://chengde.meituan.com': '承德', 'https://changshu.meituan.com': '常熟',
        'https://chifeng.meituan.com': '赤峰', 'https://changjiangxian.meituan.com': '昌江黎族自治县',
        'https://chaozhou.meituan.com': '潮州', 'https://ch.meituan.com': '巢湖', 'https://cg.meituan.com': '长葛',
        'https://cangnan.meituan.com': '苍南', 'https://changyi.meituan.com': '昌邑', 'https://conghua.meituan.com': '从化',
        'https://chizhou.meituan.com': '池州', 'https://cy.meituan.com': '朝阳', 'https://chx.meituan.com': '长兴',
        'https://chenggu.meituan.com': '城固', 'https://changle.meituan.com': '长乐', 'https://cmx.meituan.com': '澄迈县',
        'https://cx.meituan.com': '楚雄', 'https://chongzhou.meituan.com': '崇州', 'https://chongzuo.meituan.com': '崇左',
        'https://ca.meituan.com': '淳安', 'https://chengdexian.meituan.com': '承德县', 'https://changlecl.meituan.com': '昌乐',
        'https://caofeidian.meituan.com': '曹妃甸', 'https://cixian.meituan.com': '磁县',
        'https://changyuan.meituan.com': '长垣市', 'https://chengan.meituan.com': '成安',
        'https://changli.meituan.com': '昌黎', 'https://cenxi.meituan.com': '岑溪', 'https://chiping.meituan.com': '茌平区',
        'https://caoxian.meituan.com': '曹县', 'https://changji.meituan.com': '昌吉', 'https://changting.meituan.com': '长汀',
        'https://chaoan.meituan.com': '潮安', 'https://changshou.meituan.com': '长寿',
        'https://changshan.meituan.com': '常山', 'https://chishui.meituan.com': '赤水', 'https://cili.meituan.com': '慈利',
        'https://changningshi.meituan.com': '常宁市', 'https://chalingxian.meituan.com': '茶陵',
        'https://changfengxian.meituan.com': '长丰县', 'https://cangxixian.meituan.com': '苍溪县',
        'https://changqingqu.meituan.com': '长清区', 'https://chongmingqu.meituan.com': '崇明区',
        'https://chengwuxian.meituan.com': '成武县', 'https://chengjiangxian.meituan.com': '澄江市',
        'https://cb.meituan.com': '赤壁', 'https://changdu.meituan.com': '昌都', 'https://dl.meituan.com': '大连',
        'https://dg.meituan.com': '东莞', 'https://dt.meituan.com': '大同', 'https://dq.meituan.com': '大庆',
        'https://dandong.meituan.com': '丹东', 'https://dy.meituan.com': '东营', 'https://dz.meituan.com': '德州',
        'https://deyang.meituan.com': '德阳', 'https://dazhou.meituan.com': '达州', 'https://dengzhou.meituan.com': '邓州',
        'https://dali.meituan.com': '大理', 'https://dsq.meituan.com': '大石桥', 'https://djy.meituan.com': '都江堰',
        'https://dx.meituan.com': '定西', 'https://danyang.meituan.com': '丹阳', 'https://danzhou.meituan.com': '儋州',
        'https://dongyang.meituan.com': '东阳', 'https://dengfeng.meituan.com': '登封', 'https://df.meituan.com': '大丰',
        'https://dongtai.meituan.com': '东台', 'https://dazhu.meituan.com': '大竹', 'https://dangyang.meituan.com': '当阳',
        'https://deqing.meituan.com': '德清', 'https://dongkengzhen.meituan.com': '东坑镇',
        'https://dehuishi.meituan.com': '德惠市', 'https://dazuqu.meituan.com': '大足区', 'https://daye.meituan.com': '大冶',
        'https://dongxing.meituan.com': '东兴', 'https://dbs.meituan.com': '调兵山', 'https://dengta.meituan.com': '灯塔',
        'https://dawuxia.meituan.com': '大悟县', 'https://datongshi.meituan.com': '大通',
        'https://dongfang.meituan.com': '东方', 'https://dongping.meituan.com': '东平', 'https://dianbai.meituan.com': '电白',
        'https://donghai.meituan.com': '东海', 'https://dingzhou.meituan.com': '定州', 'https://dancheng.meituan.com': '郸城',
        'https://dalixian.meituan.com': '大荔', 'https://dalateqi.meituan.com': '达拉特旗',
        'https://donggang.meituan.com': '东港', 'https://dawa.meituan.com': '大洼', 'https://dayi.meituan.com': '大邑',
        'https://dangshan.meituan.com': '砀山', 'https://dunhua.meituan.com': '敦化', 'https://dongguang.meituan.com': '东光',
        'https://daoxian.meituan.com': '道县', 'https://daanshi.meituan.com': '大安市',
        'https://dinganxian.meituan.com': '定安县', 'https://dianjiang.meituan.com': '垫江',
        'https://dongmingxian.meituan.com': '东明县', 'https://dingtaoqu.meituan.com': '定陶区',
        'https://dingbianxian.meituan.com': '定边县', 'https://dachangzizhixian.meituan.com': '大厂回族自治县',
        'https://dingyuanxian.meituan.com': '定远县', 'https://dongexian.meituan.com': '东阿县',
        'https://dxal.meituan.com': '大兴安岭', 'https://dh.meituan.com': '德宏', 'https://diqing.meituan.com': '迪庆',
        'https://dunhuang.meituan.com': '敦煌', 'https://erds.meituan.com': '鄂尔多斯', 'https://ez.meituan.com': '鄂州',
        'https://es.meituan.com': '恩施', 'https://enping.meituan.com': '恩平', 'https://ems.meituan.com': '峨眉山',
        'https://eminxian.meituan.com': '额敏县', 'https://eegn.meituan.com': '额尔古纳', 'https://fz.meituan.com': '福州',
        'https://fs.meituan.com': '佛山', 'https://fy.meituan.com': '阜阳', 'https://fuz.meituan.com': '抚州',
        'https://fushun.meituan.com': '抚顺', 'https://fx.meituan.com': '阜新', 'https://fl.meituan.com': '涪陵',
        'https://fuqing.meituan.com': '福清', 'https://fenghua.meituan.com': '奉化', 'https://fc.meituan.com': '肥城',
        'https://fuyangfy.meituan.com': '富阳', 'https://fn.meituan.com': '阜宁', 'https://fcg.meituan.com': '防城港',
        'https://fuminxian.meituan.com': '富民', 'https://fengcheng.meituan.com': '凤城',
        'https://fenyang.meituan.com': '汾阳', 'https://fukang.meituan.com': '阜康', 'https://fch.meituan.com': '丰城',
        'https://fanxian.meituan.com': '范县', 'https://fanchang.meituan.com': '繁昌',
        'https://feixiang.meituan.com': '肥乡区', 'https://fengqiu.meituan.com': '封丘', 'https://fufeng.meituan.com': '扶风',
        'https://fh.meituan.com': '凤凰', 'https://fusong.meituan.com': '抚松', 'https://fushunxian.meituan.com': '富顺',
        'https://feixian.meituan.com': '费县', 'https://fogang.meituan.com': '佛冈', 'https://fengning.meituan.com': '丰宁',
        'https://fugou.meituan.com': '扶沟', 'https://fengtai.meituan.com': '凤台', 'https://fengxin.meituan.com': '奉新',
        'https://fangcheng.meituan.com': '方城', 'https://fuyuanxian.meituan.com': '富源县',
        'https://fenyi.meituan.com': '分宜', 'https://fusuixian.meituan.com': '扶绥县',
        'https://feixixian.meituan.com': '肥西县', 'https://fanzhixian.meituan.com': '繁峙县',
        'https://fengxiangxian.meituan.com': '凤翔县', 'https://fuan.meituan.com': '福安',
        'https://fudingshi.meituan.com': '福鼎市', 'https://fuguxian.meituan.com': '府谷县',
        'https://fengjie.meituan.com': '奉节', 'https://fengdu.meituan.com': '丰都',
        'https://feidongxian.meituan.com': '肥东县', 'https://fengxian.meituan.com': '丰县', 'https://gz.meituan.com': '广州',
        'https://gy.meituan.com': '贵阳', 'https://ganzhou.meituan.com': '赣州', 'https://gg.meituan.com': '贵港',
        'https://gl.meituan.com': '桂林', 'https://ga.meituan.com': '广安', 'https://gaozhou.meituan.com': '高州',
        'https://gongyishi.meituan.com': '巩义', 'https://gm.meituan.com': '高密', 'https://gbd.meituan.com': '高碑店',
        'https://guangyuan.meituan.com': '广元', 'https://gaoyou.meituan.com': '高邮', 'https://gr.meituan.com': '广饶',
        'https://guanxian.meituan.com': '固安县', 'https://gp.meituan.com': '桂平', 'https://gzl.meituan.com': '公主岭',
        'https://guangshanxian.meituan.com': '光山县', 'https://gh.meituan.com': '广汉', 'https://gc.meituan.com': '藁城',
        'https://gaoping.meituan.com': '高平', 'https://guangze.meituan.com': '光泽', 'https://guyuan.meituan.com': '固原',
        'https://gaochunqu.meituan.com': '高淳区', 'https://gaizhou.meituan.com': '盖州', 'https://gujiao.meituan.com': '古交',
        'https://geermu.meituan.com': '格尔木', 'https://gushixian.meituan.com': '固始县',
        'https://guanyun.meituan.com': '灌云', 'https://guannan.meituan.com': '灌南', 'https://ganyu.meituan.com': '赣榆',
        'https://gaoan.meituan.com': '高安', 'https://guangde.meituan.com': '广德市',
        'https://gongqingcheng.meituan.com': '共青城', 'https://gaoyang.meituan.com': '高阳',
        'https://gaoling.meituan.com': '高陵', 'https://gongan.meituan.com': '公安', 'https://gj.meituan.com': '个旧',
        'https://gulangyu.meituan.com': '鼓浪屿', 'https://gaoxiong.meituan.com': '高雄', 'https://guoluo.meituan.com': '果洛',
        'https://gn.meituan.com': '甘南', 'https://ganzi.meituan.com': '甘孜', 'https://hz.meituan.com': '杭州',
        'https://hf.meituan.com': '合肥', 'https://hrb.meituan.com': '哈尔滨', 'https://huzhou.meituan.com': '湖州',
        'https://hu.meituan.com': '呼和浩特', 'https://ha.meituan.com': '淮安', 'https://haikou.meituan.com': '海口',
        'https://hd.meituan.com': '邯郸', 'https://hy.meituan.com': '衡阳', 'https://huizhou.meituan.com': '惠州',
        'https://hs.meituan.com': '衡水', 'https://hshi.meituan.com': '黄石', 'https://hg.meituan.com': '黄冈',
        'https://hld.meituan.com': '葫芦岛', 'https://hh.meituan.com': '怀化', 'https://hn.meituan.com': '淮南',
        'https://heze.meituan.com': '菏泽', 'https://hegang.meituan.com': '鹤岗', 'https://hb.meituan.com': '鹤壁',
        'https://heihe.meituan.com': '黑河', 'https://hengdian.meituan.com': '横店', 'https://haian.meituan.com': '海安',
        'https://hlbe.meituan.com': '呼伦贝尔', 'https://huaibei.meituan.com': '淮北', 'https://heyuan.meituan.com': '河源',
        'https://hezhou.meituan.com': '贺州', 'https://hc.meituan.com': '河池', 'https://honghe.meituan.com': '红河',
        'https://hanzhong.meituan.com': '汉中', 'https://hechuan.meituan.com': '合川', 'https://huazhou.meituan.com': '化州',
        'https://huangshan.meituan.com': '黄山', 'https://haiyang.meituan.com': '海阳', 'https://hm.meituan.com': '海门',
        'https://haicheng.meituan.com': '海城', 'https://huiyang.meituan.com': '惠阳', 'https://haining.meituan.com': '海宁',
        'https://huidong.meituan.com': '惠东', 'https://hekou.meituan.com': '河口', 'https://huarong.meituan.com': '华容',
        'https://hami.meituan.com': '哈密', 'https://huayin.meituan.com': '华阴', 'https://houma.meituan.com': '侯马',
        'https://hj.meituan.com': '河津', 'https://huozhou.meituan.com': '霍州', 'https://huanghua.meituan.com': '黄骅',
        'https://hl.meituan.com': '海林', 'https://haiyan.meituan.com': '海盐', 'https://haidong.meituan.com': '海东',
        'https://huaiyang.meituan.com': '淮阳区', 'https://hanyin.meituan.com': '汉阴', 'https://hanshan.meituan.com': '含山',
        'https://hexian.meituan.com': '和县', 'https://huxian.meituan.com': '户县', 'https://huixian.meituan.com': '辉县',
        'https://huairen.meituan.com': '怀仁市', 'https://huaxian.meituan.com': '滑县', 'https://huian.meituan.com': '惠安',
        'https://hancheng.meituan.com': '韩城', 'https://heshan.meituan.com': '鹤山', 'https://huating.meituan.com': '华亭市',
        'https://hongtong.meituan.com': '洪洞', 'https://huadian.meituan.com': '桦甸', 'https://huinan.meituan.com': '辉南',
        'https://honghu.meituan.com': '洪湖', 'https://haicang.meituan.com': '海沧', 'https://huoqiu.meituan.com': '霍邱',
        'https://hunchun.meituan.com': '珲春', 'https://huaining.meituan.com': '怀宁',
        'https://huaiyuanxian.meituan.com': '怀远县', 'https://huizexian.meituan.com': '会泽县',
        'https://hejianshi.meituan.com': '河间市', 'https://hepuxian.meituan.com': '合浦县',
        'https://hengyangxian.meituan.com': '衡阳县', 'https://hengshanxian.meituan.com': '衡山县',
        'https://hengdongxian.meituan.com': '衡东县', 'https://huangchuanxian.meituan.com': '潢川县',
        'https://helanxian.meituan.com': '贺兰县', 'https://hannanqu.meituan.com': '汉南区',
        'https://hailunshi.meituan.com': '海伦市', 'https://hejiangxian.meituan.com': '合江县',
        'https://huanxian.meituan.com': '环县', 'https://huanglingxian.meituan.com': '黄陵县',
        'https://huachuanxian.meituan.com': '桦川县', 'https://hengshanqu.meituan.com': '横山区',
        'https://hyhs.meituan.com': '胡杨河市', 'https://ht.meituan.com': '和田', 'https://hualian.meituan.com': '花莲',
        'https://hengchun.meituan.com': '恒春', 'https://huangnan.meituan.com': '黄南', 'https://hnz.meituan.com': '海南州',
        'https://hx.meituan.com': '海西', 'https://haibei.meituan.com': '海北', 'https://hk.meituan.com': '香港',
        'https://jn.meituan.com': '济南', 'https://jl.meituan.com': '吉林', 'https://jiangyin.meituan.com': '江阴',
        'https://jx.meituan.com': '嘉兴', 'https://jh.meituan.com': '金华', 'https://jm.meituan.com': '江门',
        'https://jining.meituan.com': '济宁', 'https://jingzhou.meituan.com': '荆州', 'https://jiaozuo.meituan.com': '焦作',
        'https://jinjiang.meituan.com': '晋江市', 'https://jy.meituan.com': '揭阳', 'https://jingmen.meituan.com': '荆门',
        'https://jj.meituan.com': '九江', 'https://jms.meituan.com': '佳木斯', 'https://jinzhou.meituan.com': '锦州',
        'https://jintan.meituan.com': '金坛', 'https://jiyuan.meituan.com': '济源', 'https://jdz.meituan.com': '景德镇',
        'https://jq.meituan.com': '酒泉', 'https://jixi.meituan.com': '鸡西', 'https://jz.meituan.com': '晋中',
        'https://jingjiang.meituan.com': '靖江', 'https://ja.meituan.com': '吉安', 'https://js.meituan.com': '嘉善',
        'https://jr.meituan.com': '句容', 'https://jiaozhou.meituan.com': '胶州', 'https://jimo.meituan.com': '即墨',
        'https://jincheng.meituan.com': '晋城', 'https://jiangdu.meituan.com': '江都',
        'https://jiangshan.meituan.com': '江山', 'https://jinchang.meituan.com': '金昌', 'https://jianhu.meituan.com': '建湖',
        'https://jinzhoushi.meituan.com': '晋州', 'https://jyg.meituan.com': '嘉峪关', 'https://jd.meituan.com': '建德',
        'https://jianyang.meituan.com': '简阳', 'https://jiexiu.meituan.com': '介休',
        'https://jingdongyizuzizh.meituan.com': '景东彝族自治县', 'https://jiutai.meituan.com': '九台',
        'https://jingguxian.meituan.com': '景谷', 'https://jingxixian.meituan.com': '靖西市',
        'https://jiaohe.meituan.com': '蛟河', 'https://jianyangjy.meituan.com': '建阳', 'https://jiaxian.meituan.com': '郏县',
        'https://jintang.meituan.com': '金堂', 'https://jianli.meituan.com': '监利', 'https://jiangjin.meituan.com': '江津',
        'https://juye.meituan.com': '巨野', 'https://jiaxiang.meituan.com': '嘉祥', 'https://jinxiang.meituan.com': '金乡',
        'https://jinyun.meituan.com': '缙云', 'https://jingshan.meituan.com': '京山市', 'https://jiangyou.meituan.com': '江油',
        'https://junan.meituan.com': '莒南', 'https://jingyangxian.meituan.com': '泾阳县', 'https://jinhu.meituan.com': '金湖',
        'https://jimei.meituan.com': '集美', 'https://jinsha.meituan.com': '金沙', 'https://jingxian.meituan.com': '泾县',
        'https://jianxian.meituan.com': '吉安县', 'https://jishuixian.meituan.com': '吉水县',
        'https://jiangchuanxian.meituan.com': '江川县', 'https://jianghuayaozuziz.meituan.com': '江华瑶族自治县',
        'https://jinningxian.meituan.com': '晋宁区', 'https://jiangyong.meituan.com': '江永',
        'https://jianshuixian.meituan.com': '建水县', 'https://juanchengxian.meituan.com': '鄄城县',
        'https://jingbian.meituan.com': '靖边', 'https://jiayuxian.meituan.com': '嘉鱼县',
        'https://jzqixian.meituan.com': '祁县', 'https://jinghexian.meituan.com': '精河县',
        'https://jianshi.meituan.com': '集安', 'https://jiayi.meituan.com': '嘉义市', 'https://jilong.meituan.com': '基隆',
        'https://jgs.meituan.com': '井冈山', 'https://jzg.meituan.com': '九寨沟', 'https://km.meituan.com': '昆明',
        'https://kunshan.meituan.com': '昆山', 'https://kaifeng.meituan.com': '开封', 'https://klmy.meituan.com': '克拉玛依',
        'https://kp.meituan.com': '开平', 'https://krl.meituan.com': '库尔勒', 'https://kaihua.meituan.com': '开化',
        'https://kkdls.meituan.com': '可克达拉市', 'https://kaiyuanshi.meituan.com': '开远市', 'https://kt.meituan.com': '奎屯',
        'https://kys.meituan.com': '昆玉市', 'https://kenli.meituan.com': '垦利', 'https://kuancheng.meituan.com': '宽城',
        'https://kuche.meituan.com': '库车市', 'https://kangxian.meituan.com': '康县', 'https://kaiyang.meituan.com': '开阳',
        'https://kaizhouqu.meituan.com': '开州区', 'https://kl.meituan.com': '凯里', 'https://kending.meituan.com': '垦丁',
        'https://ks.meituan.com': '喀什地区', 'https://kz.meituan.com': '克州', 'https://lyg.meituan.com': '连云港',
        'https://linyi.meituan.com': '临沂', 'https://luoyang.meituan.com': '洛阳', 'https://liuzhou.meituan.com': '柳州',
        'https://lz.meituan.com': '兰州', 'https://lc.meituan.com': '聊城', 'https://lf.meituan.com': '廊坊',
        'https://liaoyang.meituan.com': '辽阳', 'https://lishui.meituan.com': '丽水', 'https://la.meituan.com': '六安',
        'https://ls.meituan.com': '乐山', 'https://lasa.meituan.com': '拉萨', 'https://ly.meituan.com': '龙岩',
        'https://linfen.meituan.com': '临汾', 'https://linzhou.meituan.com': '林州', 'https://lb.meituan.com': '来宾',
        'https://luzhou.meituan.com': '泸州', 'https://liaoyuan.meituan.com': '辽源', 'https://lvliang.meituan.com': '吕梁',
        'https://lps.meituan.com': '六盘水', 'https://lj.meituan.com': '丽江', 'https://lw.meituan.com': '莱芜',
        'https://luohe.meituan.com': '漯河', 'https://liyang.meituan.com': '溧阳', 'https://linhai.meituan.com': '临海',
        'https://lx.meituan.com': '兰溪', 'https://lk.meituan.com': '龙口', 'https://leiyang.meituan.com': '耒阳',
        'https://laizhou.meituan.com': '莱州', 'https://linan.meituan.com': '临安', 'https://laiyang.meituan.com': '莱阳',
        'https://lufeng.meituan.com': '陆丰', 'https://liuyang.meituan.com': '浏阳', 'https://lianjiang.meituan.com': '廉江',
        'https://ld.meituan.com': '娄底', 'https://liangshan.meituan.com': '凉山',
        'https://luquanxian.meituan.com': '禄劝彝族苗族自治县', 'https://lincang.meituan.com': '临沧',
        'https://linquanxian.meituan.com': '临泉县', 'https://lingbao.meituan.com': '灵宝', 'https://lsj.meituan.com': '冷水江',
        'https://ll.meituan.com': '乐陵', 'https://linxia.meituan.com': '临夏', 'https://lh.meituan.com': '龙海',
        'https://liling.meituan.com': '醴陵', 'https://laixi.meituan.com': '莱西', 'https://lechang.meituan.com': '乐昌',
        'https://lp.meituan.com': '乐平', 'https://langzhong.meituan.com': '阆中', 'https://luquan.meituan.com': '鹿泉',
        'https://lichuan.meituan.com': '利川', 'https://lhk.meituan.com': '老河口', 'https://linghai.meituan.com': '凌海',
        'https://luannan.meituan.com': '滦南', 'https://lingshan.meituan.com': '灵山', 'https://lianzhou.meituan.com': '连州',
        'https://lingshui.meituan.com': '陵水', 'https://lingwushi.meituan.com': '灵武市',
        'https://lianjiangxian.meituan.com': '连江', 'https://linqu.meituan.com': '临朐',
        'https://laoting.meituan.com': '乐亭', 'https://luanxian.meituan.com': '滦州市',
        'https://luancheng.meituan.com': '栾城', 'https://lushanls.meituan.com': '鲁山',
        'https://lingshi.meituan.com': '灵石', 'https://linzhang.meituan.com': '临漳', 'https://lintong.meituan.com': '临潼',
        'https://lantian.meituan.com': '蓝田', 'https://lq.meituan.com': '临清', 'https://longchang.meituan.com': '隆昌市',
        'https://luyi.meituan.com': '鹿邑', 'https://liuhe.meituan.com': '柳河', 'https://linyixian.meituan.com': '临猗',
        'https://liangshanxian.meituan.com': '梁山', 'https://lijin.meituan.com': '利津',
        'https://linyily.meituan.com': '临邑', 'https://longquan.meituan.com': '龙泉',
        'https://lingchuan.meituan.com': '陵川', 'https://longyao.meituan.com': '隆尧', 'https://leizhou.meituan.com': '雷州',
        'https://luanchuan.meituan.com': '栾川', 'https://longyou.meituan.com': '龙游', 'https://lanling.meituan.com': '兰陵',
        'https://linshu.meituan.com': '临沭', 'https://lianshui.meituan.com': '涟水', 'https://lixian.meituan.com': '澧县',
        'https://liaozhong.meituan.com': '辽中', 'https://luopingxian.meituan.com': '罗平县',
        'https://lianyuanshi.meituan.com': '涟源市', 'https://lujiangxian.meituan.com': '庐江县',
        'https://linying.meituan.com': '临颍', 'https://lanshan.meituan.com': '蓝山', 'https://longhui.meituan.com': '隆回',
        'https://luxi.meituan.com': '芦溪', 'https://lushixian.meituan.com': '卢氏县',
        'https://longhuaxian.meituan.com': '隆化县', 'https://luoningxian.meituan.com': '洛宁',
        'https://lankaoxian.meituan.com': '兰考县', 'https://linli.meituan.com': '临澧', 'https://lixin.meituan.com': '利辛',
        'https://lingqiuxian.meituan.com': '灵丘县', 'https://lufengxian.meituan.com': '禄丰县',
        'https://lishuiqu.meituan.com': '溧水区', 'https://luxian.meituan.com': '泸县',
        'https://luochuanxian.meituan.com': '洛川县', 'https://luodingshi.meituan.com': '罗定市',
        'https://ledong.meituan.com': '乐东', 'https://liangping.meituan.com': '梁平',
        'https://lingaoxian.meituan.com': '临高县', 'https://luoyuanxian.meituan.com': '罗源县',
        'https://luchuanxian.meituan.com': '陆川县', 'https://linjiang.meituan.com': '临江', 'https://ln.meituan.com': '陇南',
        'https://linzhi.meituan.com': '林芝', 'https://my.meituan.com': '绵阳', 'https://mdj.meituan.com': '牡丹江',
        'https://mm.meituan.com': '茂名', 'https://mas.meituan.com': '马鞍山', 'https://mz.meituan.com': '梅州',
        'https://ms.meituan.com': '眉山', 'https://mentougouqu.meituan.com': '门头沟区', 'https://mishan.meituan.com': '密山',
        'https://mzl.meituan.com': '满洲里', 'https://mhk.meituan.com': '梅河口', 'https://ml.meituan.com': '汨罗',
        'https://mg.meituan.com': '明光', 'https://mc.meituan.com': '麻城', 'https://mengzhou.meituan.com': '孟州',
        'https://mingshuixian.meituan.com': '明水县', 'https://mengjin.meituan.com': '孟津',
        'https://muping.meituan.com': '牟平', 'https://meixian.meituan.com': '眉县', 'https://minquan.meituan.com': '民权',
        'https://mianchi.meituan.com': '渑池', 'https://mianzhu.meituan.com': '绵竹', 'https://mengyin.meituan.com': '蒙阴',
        'https://mengzishi.meituan.com': '蒙自市', 'https://mengcheng.meituan.com': '蒙城',
        'https://menglaxian.meituan.com': '勐腊县', 'https://miyixian.meituan.com': '米易县',
        'https://minhouxian.meituan.com': '闽侯县', 'https://miaoli.meituan.com': '苗栗', 'https://mh.meituan.com': '漠河',
        'https://mingwangxing.meituan.com': '冥王星', 'https://nj.meituan.com': '南京', 'https://nb.meituan.com': '宁波',
        'https://nn.meituan.com': '南宁', 'https://nc.meituan.com': '南昌', 'https://nt.meituan.com': '南通',
        'https://ny.meituan.com': '南阳', 'https://nd.meituan.com': '宁德', 'https://nanchong.meituan.com': '南充',
        'https://np.meituan.com': '南平', 'https://scnj.meituan.com': '内江', 'https://nh.meituan.com': '宁海',
        'https://na.meituan.com': '南安', 'https://nax.meituan.com': '农安县', 'https://nx.meituan.com': '宁乡',
        'https://ns.meituan.com': '南沙', 'https://nanchuan.meituan.com': '南川', 'https://nehe.meituan.com': '讷河',
        'https://nanxiong.meituan.com': '南雄', 'https://nenjiangxian.meituan.com': '嫩江市',
        'https://ningyuanxian.meituan.com': '宁远县', 'https://nanling.meituan.com': '南陵',
        'https://ningyang.meituan.com': '宁阳', 'https://ningguo.meituan.com': '宁国', 'https://ningjin.meituan.com': '宁晋',
        'https://ningjinnj.meituan.com': '宁津', 'https://neiqiu.meituan.com': '内丘', 'https://nangong.meituan.com': '南宫',
        'https://neihuang.meituan.com': '内黄', 'https://nanhe.meituan.com': '南和', 'https://nanbuxian.meituan.com': '南部县',
        'https://nanpixian.meituan.com': '南皮县', 'https://ninglingxian.meituan.com': '宁陵',
        'https://nanzhengxian.meituan.com': '南郑区', 'https://ninglangyizuzizh.meituan.com': '宁蒗彝族自治县',
        'https://nanle.meituan.com': '南乐', 'https://nantou.meituan.com': '南投', 'https://nq.meituan.com': '那曲',
        'https://nujiang.meituan.com': '怒江', 'https://pt.meituan.com': '莆田', 'https://pj.meituan.com': '盘锦',
        'https://pds.meituan.com': '平顶山', 'https://puyang.meituan.com': '濮阳', 'https://px.meituan.com': '萍乡',
        'https://panzhihua.meituan.com': '攀枝花', 'https://pe.meituan.com': '普洱', 'https://pl.meituan.com': '平凉',
        'https://pz.meituan.com': '邳州', 'https://ph.meituan.com': '平湖', 'https://pn.meituan.com': '普宁',
        'https://pd.meituan.com': '平度', 'https://pengzhou.meituan.com': '彭州', 'https://penglai.meituan.com': '蓬莱',
        'https://pingyang.meituan.com': '平阳', 'https://peixian.meituan.com': '沛县', 'https://pingyu.meituan.com': '平舆',
        'https://pujiang.meituan.com': '浦江', 'https://pingyuan.meituan.com': '平原', 'https://pingtan.meituan.com': '平潭',
        'https://pulandian.meituan.com': '普兰店', 'https://pucheng.meituan.com': '蒲城',
        'https://panxian.meituan.com': '盘州市', 'https://pingjiang.meituan.com': '平江',
        'https://puyangxian.meituan.com': '濮阳县', 'https://pingshan.meituan.com': '平山',
        'https://pingquan.meituan.com': '平泉市', 'https://pingyi.meituan.com': '平邑', 'https://panshi.meituan.com': '磐石',
        'https://poyang.meituan.com': '鄱阳', 'https://pingyao.meituan.com': '平遥', 'https://pingguo.meituan.com': '平果市',
        'https://pingluoxian.meituan.com': '平罗县', 'https://pingyinxian.meituan.com': '平阴县',
        'https://pingluxian.meituan.com': '平陆县', 'https://pingchangxian.meituan.com': '平昌县',
        'https://pingnanxian.meituan.com': '平南县', 'https://pengshuizizhixia.meituan.com': '彭水苗族土家族自治县',
        'https://pdx.meituan.com': '平定县', 'https://penghu.meituan.com': '澎湖', 'https://qd.meituan.com': '青岛',
        'https://qhd.meituan.com': '秦皇岛', 'https://qz.meituan.com': '泉州', 'https://qj.meituan.com': '曲靖',
        'https://quzhou.meituan.com': '衢州', 'https://qingyuan.meituan.com': '清远', 'https://qqhr.meituan.com': '齐齐哈尔',
        'https://qinzhou.meituan.com': '钦州', 'https://qth.meituan.com': '七台河', 'https://qingyang.meituan.com': '庆阳',
        'https://qa.meituan.com': '迁安', 'https://qingzhou.meituan.com': '青州', 'https://qidong.meituan.com': '启东',
        'https://qianjiang.meituan.com': '潜江', 'https://qdn.meituan.com': '黔东南', 'https://qxn.meituan.com': '黔西南',
        'https://qianjiangqu.meituan.com': '黔江区', 'https://qingtongxiashi.meituan.com': '青铜峡市',
        'https://qh.meituan.com': '琼海', 'https://qy.meituan.com': '沁阳', 'https://ql.meituan.com': '邛崃',
        'https://qihe.meituan.com': '齐河', 'https://qn.meituan.com': '黔南', 'https://qixian.meituan.com': '淇县',
        'https://quanjiao.meituan.com': '全椒', 'https://qixia.meituan.com': '栖霞', 'https://qingtian.meituan.com': '青田',
        'https://qinghe.meituan.com': '清河', 'https://qingyun.meituan.com': '庆云', 'https://qianshan.meituan.com': '潜山市',
        'https://qingxian.meituan.com': '青县', 'https://qidongxian.meituan.com': '祁东县',
        'https://qinganxian.meituan.com': '庆安县', 'https://qixiankaifeng.meituan.com': '杞县',
        'https://qinggangxian.meituan.com': '青冈县', 'https://qishanxian.meituan.com': '岐山县',
        'https://qiongzhong.meituan.com': '琼中', 'https://qingyangxian.meituan.com': '青阳县',
        'https://qingzhen.meituan.com': '清镇', 'https://qijiang.meituan.com': '綦江', 'https://qingxu.meituan.com': '清徐',
        'https://qianxixian.meituan.com': '迁西县', 'https://qishizhen.meituan.com': '企石镇',
        'https://qingfeng.meituan.com': '清丰', 'https://qf.meituan.com': '曲阜', 'https://rizhao.meituan.com': '日照',
        'https://ruian.meituan.com': '瑞安', 'https://rc.meituan.com': '荣成', 'https://rs.meituan.com': '乳山',
        'https://rg.meituan.com': '如皋', 'https://rz.meituan.com': '汝州', 'https://rudong.meituan.com': '如东',
        'https://rh.meituan.com': '仁怀', 'https://rj.meituan.com': '瑞金', 'https://rongchangqu.meituan.com': '荣昌区',
        'https://renshou.meituan.com': '仁寿', 'https://renqiu.meituan.com': '任丘', 'https://ruyang.meituan.com': '汝阳',
        'https://ruili.meituan.com': '瑞丽', 'https://renxian.meituan.com': '任县',
        'https://ruchengxian.meituan.com': '汝城县', 'https://rongxian.meituan.com': '容县',
        'https://ruichang.meituan.com': '瑞昌', 'https://rkz.meituan.com': '日喀则', 'https://sh.meituan.com': '上海',
        'https://sz.meituan.com': '深圳', 'https://sjz.meituan.com': '石家庄', 'https://su.meituan.com': '苏州',
        'https://sy.meituan.com': '沈阳', 'https://sanya.meituan.com': '三亚', 'https://st.meituan.com': '汕头',
        'https://sx.meituan.com': '绍兴', 'https://songyuan.meituan.com': '松原', 'https://sg.meituan.com': '韶关',
        'https://shaoyang.meituan.com': '邵阳', 'https://suqian.meituan.com': '宿迁', 'https://shiyan.meituan.com': '十堰',
        'https://suzhousz.meituan.com': '宿州', 'https://sd.meituan.com': '顺德', 'https://sr.meituan.com': '上饶',
        'https://sq.meituan.com': '商丘', 'https://shz.meituan.com': '石河子', 'https://smx.meituan.com': '三门峡',
        'https://suizhou.meituan.com': '随州', 'https://suihua.meituan.com': '绥化', 'https://sys.meituan.com': '双鸭山',
        'https://sw.meituan.com': '汕尾', 'https://suining.meituan.com': '遂宁', 'https://sl.meituan.com': '商洛',
        'https://szs.meituan.com': '石嘴山', 'https://sp.meituan.com': '四平', 'https://sm.meituan.com': '三明',
        'https://ss.meituan.com': '石狮', 'https://shangyu.meituan.com': '上虞', 'https://shouguang.meituan.com': '寿光',
        'https://shengzhou.meituan.com': '嵊州', 'https://shuyang.meituan.com': '沭阳', 'https://sheyang.meituan.com': '射阳',
        'https://sanhe.meituan.com': '三河', 'https://shuozhou.meituan.com': '朔州', 'https://shucheng.meituan.com': '舒城',
        'https://shenxian.meituan.com': '莘县', 'https://shilinxian.meituan.com': '石林彝族自治县',
        'https://songmingxian.meituan.com': '嵩明县', 'https://shaoshan.meituan.com': '韶山',
        'https://shahe.meituan.com': '沙河', 'https://sihui.meituan.com': '四会', 'https://songzi.meituan.com': '松滋',
        'https://shulan.meituan.com': '舒兰', 'https://shaodong.meituan.com': '邵东市', 'https://suixian.meituan.com': '睢县',
        'https://siyang.meituan.com': '泗阳', 'https://shawan.meituan.com': '沙湾', 'https://shexian.meituan.com': '涉县',
        'https://shs.meituan.com': '双河市', 'https://suizhong.meituan.com': '绥中', 'https://shanggao.meituan.com': '上高',
        'https://shiquan.meituan.com': '石泉', 'https://sihong.meituan.com': '泗洪', 'https://shanxian.meituan.com': '单县',
        'https://shenqiu.meituan.com': '沈丘', 'https://sanmen.meituan.com': '三门',
        'https://suiningxian.meituan.com': '睢宁', 'https://shangcai.meituan.com': '上蔡',
        'https://suichang.meituan.com': '遂昌', 'https://shidao.meituan.com': '石岛', 'https://shifang.meituan.com': '什邡',
        'https://shanghang.meituan.com': '上杭', 'https://songxian.meituan.com': '嵩县',
        'https://sanyuanxian.meituan.com': '三原县', 'https://shehong.meituan.com': '射洪市',
        'https://shanghe.meituan.com': '商河', 'https://sishui.meituan.com': '泗水', 'https://sheqi.meituan.com': '社旗',
        'https://sixian.meituan.com': '泗县', 'https://shenzhoushi.meituan.com': '深州市',
        'https://shanglinxian.meituan.com': '上林县', 'https://shangshuixian.meituan.com': '商水县',
        'https://shuangfeng.meituan.com': '双峰', 'https://suichuan.meituan.com': '遂川',
        'https://shangli.meituan.com': '上栗', 'https://shachexian.meituan.com': '莎车县',
        'https://suningxian.meituan.com': '肃宁县', 'https://shangchengxian.meituan.com': '商城县',
        'https://sangzhi.meituan.com': '桑植', 'https://shimen.meituan.com': '石门',
        'https://shanshanxian.meituan.com': '鄯善县', 'https://suidexian.meituan.com': '绥德县',
        'https://shaxian.meituan.com': '沙县', 'https://shenzexian.meituan.com': '深泽县',
        'https://shizhu.meituan.com': '石柱', 'https://shaowu.meituan.com': '邵武', 'https://shouxian.meituan.com': '寿县',
        'https://santaixian.meituan.com': '三台县', 'https://shandanxian.meituan.com': '山丹县',
        'https://shanzhouqu.meituan.com': '陕州区', 'https://suiningxiansnx.meituan.com': '绥宁县',
        'https://shuangcheng.meituan.com': '双城', 'https://suiping.meituan.com': '遂平', 'https://shaya.meituan.com': '沙雅',
        'https://shenmu.meituan.com': '神木市', 'https://sqs.meituan.com': '三清山', 'https://snj.meituan.com': '神农架',
        'https://sn.meituan.com': '山南', 'https://sanx.meituan.com': '三峡', 'https://tj.meituan.com': '天津',
        'https://ty.meituan.com': '太原', 'https://ts.meituan.com': '唐山', 'https://taizhou.meituan.com': '泰州',
        'https://tz.meituan.com': '台州', 'https://ta.meituan.com': '泰安', 'https://tx.meituan.com': '桐乡',
        'https://taicang.meituan.com': '太仓', 'https://tongling.meituan.com': '铜陵', 'https://tl.meituan.com': '铁岭',
        'https://tr.meituan.com': '铜仁', 'https://tc.meituan.com': '铜川', 'https://tianshui.meituan.com': '天水',
        'https://th.meituan.com': '通化', 'https://tianchang.meituan.com': '天长', 'https://tm.meituan.com': '天门',
        'https://tumushuke.meituan.com': '图木舒克', 'https://tongliao.meituan.com': '通辽',
        'https://tengzhou.meituan.com': '滕州', 'https://taishan.meituan.com': '台山', 'https://taixing.meituan.com': '泰兴',
        'https://taihexian.meituan.com': '泰和县', 'https://tongliang.meituan.com': '铜梁',
        'https://tongcheng.meituan.com': '桐城', 'https://taiqian.meituan.com': '台前', 'https://taihe.meituan.com': '太和',
        'https://tiantai.meituan.com': '天台', 'https://taigu.meituan.com': '太谷区', 'https://tengxian.meituan.com': '藤县',
        'https://tangyin.meituan.com': '汤阴', 'https://tmtyq.meituan.com': '土默特右旗', 'https://tancheng.meituan.com': '郯城',
        'https://tonglu.meituan.com': '桐庐', 'https://tongan.meituan.com': '同安', 'https://taoyuanxian.meituan.com': '桃源',
        'https://tn.meituan.com': '洮南', 'https://tonggu.meituan.com': '铜鼓', 'https://tiandongxian.meituan.com': '田东县',
        'https://taikangxian.meituan.com': '太康县', 'https://tongxuxian.meituan.com': '通许县',
        'https://tonghaixian.meituan.com': '通海县', 'https://tongyuxian.meituan.com': '通榆县',
        'https://tanghe.meituan.com': '唐河', 'https://tongxinxian.meituan.com': '同心县',
        'https://tachengshi.meituan.com': '塔城市', 'https://taiwan.meituan.com': '台湾',
        'https://tongjiangxian.meituan.com': '通江县', 'https://tonghexian.meituan.com': '通河县',
        'https://tunchangxian.meituan.com': '屯昌县', 'https://tlf.meituan.com': '吐鲁番',
        'https://taidong.meituan.com': '台东', 'https://taoyuan.meituan.com': '桃园', 'https://tac.meituan.com': '塔城',
        'https://tengchong.meituan.com': '腾冲', 'https://tb.meituan.com': '台北', 'https://taizhong.meituan.com': '台中',
        'https://tainan.meituan.com': '台南', 'https://wh.meituan.com': '武汉', 'https://wx.meituan.com': '无锡',
        'https://wz.meituan.com': '温州', 'https://wf.meituan.com': '潍坊', 'https://weihai.meituan.com': '威海',
        'https://wuhu.meituan.com': '芜湖', 'https://xj.meituan.com': '乌鲁木齐', 'https://wn.meituan.com': '渭南',
        'https://wj.meituan.com': '吴江', 'https://wenling.meituan.com': '温岭', 'https://wuhai.meituan.com': '乌海',
        'https://wanzhou.meituan.com': '万州', 'https://wuzhou.meituan.com': '梧州', 'https://wuan.meituan.com': '武安',
        'https://wlcb.meituan.com': '乌兰察布', 'https://wd.meituan.com': '文登', 'https://wc.meituan.com': '吴川',
        'https://wafangdian.meituan.com': '瓦房店', 'https://wuwei.meituan.com': '武威', 'https://wy.meituan.com': '婺源',
        'https://wuding.meituan.com': '武定', 'https://wuzhong.meituan.com': '吴忠', 'https://wugangshi.meituan.com': '武冈市',
        'https://wys.meituan.com': '武夷山', 'https://wenchang.meituan.com': '文昌', 'https://wuxue.meituan.com': '武穴',
        'https://wanning.meituan.com': '万宁', 'https://wg.meituan.com': '舞钢', 'https://wlhts.meituan.com': '乌兰浩特市',
        'https://wuzhi.meituan.com': '武陟', 'https://wusu.meituan.com': '乌苏', 'https://wuweiww.meituan.com': '无为市',
        'https://wuhuxian.meituan.com': '芜湖县', 'https://weihui.meituan.com': '卫辉', 'https://wltqq.meituan.com': '乌拉特前旗',
        'https://weishan.meituan.com': '微山', 'https://wenshang.meituan.com': '汶上', 'https://wucheng.meituan.com': '武城',
        'https://weichang.meituan.com': '围场', 'https://ws.meituan.com': '文山', 'https://wuyi.meituan.com': '武义',
        'https://wuming.meituan.com': '武鸣', 'https://weining.meituan.com': '威宁', 'https://wuyang.meituan.com': '舞阳',
        'https://wuji.meituan.com': '无极', 'https://wanrong.meituan.com': '万荣', 'https://wanzai.meituan.com': '万载',
        'https://weixian.meituan.com': '威县', 'https://wupingxian.meituan.com': '武平县',
        'https://weishixian.meituan.com': '尉氏县', 'https://wulongxian.meituan.com': '武隆县',
        'https://wuchangshi.meituan.com': '五常市', 'https://wangcangxian.meituan.com': '旺苍县',
        'https://wangkuixian.meituan.com': '望奎县', 'https://wenxian.meituan.com': '温县',
        'https://wuzhen.meituan.com': '乌镇', 'https://wds.meituan.com': '武当山', 'https://xa.meituan.com': '西安',
        'https://xm.meituan.com': '厦门', 'https://xz.meituan.com': '徐州', 'https://xf.meituan.com': '襄阳',
        'https://xiangtan.meituan.com': '湘潭', 'https://xn.meituan.com': '西宁', 'https://xuancheng.meituan.com': '宣城',
        'https://xianyang.meituan.com': '咸阳', 'https://xc.meituan.com': '许昌', 'https://xy.meituan.com': '信阳',
        'https://xt.meituan.com': '邢台', 'https://xiaogan.meituan.com': '孝感', 'https://xx.meituan.com': '新乡',
        'https://xintai.meituan.com': '新泰', 'https://xianning.meituan.com': '咸宁', 'https://xinyu.meituan.com': '新余',
        'https://xan.meituan.com': '兴安盟', 'https://xiantao.meituan.com': '仙桃', 'https://xh.meituan.com': '兴化',
        'https://bn.meituan.com': '西双版纳', 'https://xinji.meituan.com': '辛集', 'https://xinyi.meituan.com': '新沂',
        'https://xinzheng.meituan.com': '新郑', 'https://xinmi.meituan.com': '新密', 'https://xinzhou.meituan.com': '忻州',
        'https://xinyixy.meituan.com': '信宜', 'https://xingyishi.meituan.com': '兴义市',
        'https://xiegangzhen.meituan.com': '谢岗镇', 'https://xlgl.meituan.com': '锡林郭勒',
        'https://xiangxi.meituan.com': '湘西', 'https://xingyang.meituan.com': '荥阳', 'https://xiaoxian.meituan.com': '萧县',
        'https://xingning.meituan.com': '兴宁', 'https://xinmin.meituan.com': '新民',
        'https://xiangcheng.meituan.com': '项城', 'https://xiaoyi.meituan.com': '孝义',
        'https://xiangxiang.meituan.com': '湘乡', 'https://xingcheng.meituan.com': '兴城', 'https://xp.meituan.com': '兴平',
        'https://xiangshan.meituan.com': '象山', 'https://xw.meituan.com': '修武', 'https://xixian.meituan.com': '息县',
        'https://xiaochangxian.meituan.com': '孝昌县', 'https://xiangyin.meituan.com': '湘阴',
        'https://xiangshui.meituan.com': '响水', 'https://xinhua.meituan.com': '新化', 'https://xianju.meituan.com': '仙居',
        'https://xiangyuan.meituan.com': '襄垣', 'https://xuanwei.meituan.com': '宣威', 'https://xiapu.meituan.com': '霞浦',
        'https://xinan.meituan.com': '新安', 'https://xinxiangxian.meituan.com': '新乡县', 'https://xuyi.meituan.com': '盱眙',
        'https://xuwen.meituan.com': '徐闻', 'https://xiayi.meituan.com': '夏邑', 'https://xunxian.meituan.com': '浚县',
        'https://xixiang.meituan.com': '西乡', 'https://xiping.meituan.com': '西平', 'https://xinle.meituan.com': '新乐',
        'https://xinchang.meituan.com': '新昌', 'https://xuecheng.meituan.com': '薛城', 'https://xihua.meituan.com': '西华',
        'https://xishui.meituan.com': '浠水', 'https://xianghe.meituan.com': '香河', 'https://xinfeng.meituan.com': '信丰',
        'https://xincai.meituan.com': '新蔡', 'https://xupu.meituan.com': '溆浦', 'https://xichuan.meituan.com': '淅川',
        'https://xingan.meituan.com': '新干', 'https://xingguoxian.meituan.com': '兴国县',
        'https://xintian.meituan.com': '新田', 'https://xunwuxian.meituan.com': '寻乌县',
        'https://xiangyunxian.meituan.com': '祥云县', 'https://xiangchengxian.meituan.com': '襄城县',
        'https://xinning.meituan.com': '新宁', 'https://xianxian.meituan.com': '献县',
        'https://xinzhouqu.meituan.com': '新洲区', 'https://xiushantujiazumi.meituan.com': '秀山土家族苗族自治县',
        'https://xinye.meituan.com': '新野', 'https://xianyouxian.meituan.com': '仙游县',
        'https://xinjinxian.meituan.com': '新津县', 'https://xunyangxian.meituan.com': '旬阳县',
        'https://xiajin.meituan.com': '夏津', 'https://xinzhushi.meituan.com': '新竹市', 'https://xinbei.meituan.com': '新北',
        'https://xitang.meituan.com': '西塘', 'https://xgll.meituan.com': '香格里拉', 'https://yt.meituan.com': '烟台',
        'https://yz.meituan.com': '扬州', 'https://yinchuan.meituan.com': '银川', 'https://yancheng.meituan.com': '盐城',
        'https://yy.meituan.com': '岳阳', 'https://yc.meituan.com': '宜昌', 'https://yk.meituan.com': '营口',
        'https://yichun.meituan.com': '宜春', 'https://yj.meituan.com': '阳江', 'https://yuncheng.meituan.com': '运城',
        'https://yb.meituan.com': '宜宾', 'https://yl.meituan.com': '榆林', 'https://yiyang.meituan.com': '益阳',
        'https://yiwu.meituan.com': '义乌', 'https://yixing.meituan.com': '宜兴', 'https://yuyao.meituan.com': '余姚',
        'https://yueqing.meituan.com': '乐清', 'https://yulin.meituan.com': '玉林', 'https://yongzhou.meituan.com': '永州',
        'https://yongchuan.meituan.com': '永川', 'https://yf.meituan.com': '云浮', 'https://yanzhou.meituan.com': '兖州',
        'https://yingtan.meituan.com': '鹰潭', 'https://yongkang.meituan.com': '永康', 'https://yanbian.meituan.com': '延边',
        'https://yq.meituan.com': '阳泉', 'https://yd.meituan.com': '英德', 'https://yizheng.meituan.com': '仪征',
        'https://yongcheng.meituan.com': '永城', 'https://yuzhou.meituan.com': '禹州', 'https://yn.meituan.com': '伊宁',
        'https://yanan.meituan.com': '延安', 'https://yx.meituan.com': '玉溪', 'https://yichuan.meituan.com': '伊川',
        'https://yiliangxian.meituan.com': '宜良县', 'https://yanshi.meituan.com': '偃师',
        'https://yangzhong.meituan.com': '扬中', 'https://yutianxian.meituan.com': '玉田县',
        'https://yongji.meituan.com': '永济', 'https://yucheng.meituan.com': '禹城', 'https://yuxian.meituan.com': '盂县',
        'https://yangshuo.meituan.com': '阳朔', 'https://yicheng.meituan.com': '宜城', 'https://yp.meituan.com': '原平',
        'https://yidu.meituan.com': '宜都', 'https://yongningxian.meituan.com': '永宁县', 'https://yh.meituan.com': '玉环市',
        'https://yongjiaxian.meituan.com': '永嘉县', 'https://ya.meituan.com': '雅安', 'https://yongnian.meituan.com': '永年',
        'https://yangcheng.meituan.com': '阳城', 'https://yunyang.meituan.com': '云阳', 'https://yexian.meituan.com': '叶县',
        'https://yixian.meituan.com': '易县', 'https://yiyangyy.meituan.com': '宜阳', 'https://yanliang.meituan.com': '阎良',
        'https://yuanyang.meituan.com': '原阳', 'https://yuchengxian.meituan.com': '虞城',
        'https://yushan.meituan.com': '玉山', 'https://yanggu.meituan.com': '阳谷',
        'https://yunchengxian.meituan.com': '郓城', 'https://yjhlq.meituan.com': '伊金霍洛旗',
        'https://yangling.meituan.com': '杨陵', 'https://yishui.meituan.com': '沂水', 'https://yinan.meituan.com': '沂南',
        'https://yudu.meituan.com': '于都', 'https://yifeng.meituan.com': '宜丰', 'https://yingshanxian.meituan.com': '营山县',
        'https://yongan.meituan.com': '永安', 'https://yanling.meituan.com': '鄢陵', 'https://yongfeng.meituan.com': '永丰',
        'https://yongxin.meituan.com': '永新', 'https://yongxingxian.meituan.com': '永兴县',
        'https://youxian.meituan.com': '攸县', 'https://yongshunxian.meituan.com': '永顺县',
        'https://yuminxian.meituan.com': '裕民县', 'https://youyangtujiazumi.meituan.com': '酉阳土家族苗族自治县',
        'https://yingxian.meituan.com': '应县', 'https://yangshanxian.meituan.com': '阳山县',
        'https://yushushi.meituan.com': '榆树市', 'https://yuanlingxian.meituan.com': '沅陵县',
        'https://yongdengxian.meituan.com': '永登县', 'https://yutaixian.meituan.com': '鱼台县',
        'https://yizhoushi.meituan.com': '宜州区', 'https://yimashi.meituan.com': '义马市',
        'https://yuanjiang.meituan.com': '沅江', 'https://yilan.meituan.com': '宜兰', 'https://yili.meituan.com': '伊犁',
        'https://ys.meituan.com': '玉树', 'https://yich.meituan.com': '伊春', 'https://zz.meituan.com': '郑州',
        'https://zb.meituan.com': '淄博', 'https://zs.meituan.com': '中山', 'https://zhanjiang.meituan.com': '湛江',
        'https://zj.meituan.com': '镇江', 'https://zhuzhou.meituan.com': '株洲', 'https://zh.meituan.com': '珠海',
        'https://zaozhuang.meituan.com': '枣庄', 'https://zhangzhou.meituan.com': '漳州', 'https://zmd.meituan.com': '驻马店',
        'https://zhoushan.meituan.com': '舟山', 'https://zjk.meituan.com': '张家口', 'https://zq.meituan.com': '肇庆',
        'https://zunyi.meituan.com': '遵义', 'https://zjg.meituan.com': '张家港', 'https://zhuji.meituan.com': '诸暨',
        'https://zk.meituan.com': '周口', 'https://zhucheng.meituan.com': '诸城', 'https://zt.meituan.com': '昭通',
        'https://zhangye.meituan.com': '张掖', 'https://zoucheng.meituan.com': '邹城', 'https://zjj.meituan.com': '张家界',
        'https://zhuozhou.meituan.com': '涿州', 'https://zhangqiu.meituan.com': '章丘区', 'https://zg.meituan.com': '自贡',
        'https://zaoyang.meituan.com': '枣阳', 'https://zunhua.meituan.com': '遵化', 'https://zy.meituan.com': '资阳',
        'https://zhuanghe.meituan.com': '庄河', 'https://zhaoyuan.meituan.com': '招远',
        'https://zhungeerqi.meituan.com': '准格尔旗', 'https://zp.meituan.com': '邹平',
        'https://zhenxiongxian.meituan.com': '镇雄县', 'https://zhijiang.meituan.com': '枝江',
        'https://zhangpu.meituan.com': '漳浦', 'https://zhangshu.meituan.com': '樟树',
        'https://zhongjiangxian.meituan.com': '中江县', 'https://zhengding.meituan.com': '正定',
        'https://zhongmou.meituan.com': '中牟', 'https://zw.meituan.com': '中卫', 'https://zhaoxian.meituan.com': '赵县',
        'https://zhecheng.meituan.com': '柘城', 'https://zx.meituan.com': '钟祥', 'https://zhouzhi.meituan.com': '周至',
        'https://zhijiangtongzu.meituan.com': '芷江', 'https://zhijin.meituan.com': '织金',
        'https://zhangping.meituan.com': '漳平', 'https://zixingshi.meituan.com': '资兴市',
        'https://zhalantunshi.meituan.com': '扎兰屯市', 'https://zhongxian.meituan.com': '忠县',
        'https://zherong.meituan.com': '柘荣', 'https://zhongningxian.meituan.com': '中宁县',
        'https://zhanghua.meituan.com': '彰化', 'https://zhouzhuang.meituan.com': '周庄'}
CITY_TAG = {'北京': 'BJP', '上海': 'SHH', '郑州': 'ZZF', '广州': 'GZQ', '成都': 'CDW', '南京': 'NJH', '武汉': 'WHN', '西安': 'XAY',
            '杭州': 'HZH', '济南': 'JNK', '重庆': 'CQW', '深圳': 'SZQ', '长沙': 'CSQ', '天津': 'TJP', '沈阳': 'SYT', '苏州': 'SZH',
            '合肥': 'HFH', '昆明': 'KMM', '青岛': 'QDK', '石家庄': 'SJP', '厦门': 'XMS', '贵阳': 'GIW', '徐州': 'XCH', '哈尔滨': 'HBB',
            '南昌': 'NCG', '太原': 'TYV', '南宁': 'NNZ', '长春': 'CCT', '无锡': 'WXH', '宁波': 'NGH', '大连': 'DLT', '洛阳': 'LYF',
            '大理': 'DKM', '兰州': 'LZJ', '桂林': 'GLZ', '潍坊': 'WFK', '常州': 'CZH', '福州': 'FZS', '芜湖': 'WHH', '商丘': 'SQF',
            '烟台': 'YAK', '泰安': 'TMK', '丽江': 'LHM', '淄博': 'ZBK', '唐山': 'TSP', '开封': 'KFF', '珠海': 'ZHQ', '阜阳': 'FYH',
            '东莞': 'RTQ', '乌鲁木齐': 'WAR', '温州': 'RZH', '秦皇岛': 'QTP', '新乡': 'XXF', '三亚': 'SEQ', '襄阳': 'XFN', '呼和浩特': 'HHC',
            '柳州': 'LZZ', '保定': 'BDP', '信阳': 'XUN', '临沂': 'LVK', '蚌埠': 'BBH', '北海': 'BHZ', '九江': 'JJG', '绵阳': 'MYW',
            '张家界': 'DIQ', '西宁': 'XNO', '邯郸': 'HDP', '菏泽': 'HIK', '漯河': 'LON', '扬州': 'YLH', '株洲': 'ZZQ', '嘉兴': 'JXH',
            '镇江': 'ZJH', '金华': 'JBH', '南阳': 'NFF', '海口': 'VUQ', '锦州': 'JZD', '惠州': 'HCQ', '衡阳': 'HYQ', '吉林': 'JLL',
            '宜昌': 'YCN', '泉州': 'QYS', '安阳': 'AYF', '赣州': 'GZG', '遵义': 'ZYE', '拉萨': 'LSO', '昆山': 'KSH', '荆州': 'JBN',
            '威海': 'WKK', '枣庄': 'ZEK', '驻马店': 'ZDN', '济宁': 'JIK', '六安': 'UAH', '黄山': 'HKH', '南通': 'NUH', '佳木斯': 'JMB',
            '许昌': 'XCF', '绍兴': 'SOH', '台州': 'TZH', '焦作': 'JOF', '德州': 'DZP', '南充': 'NCW', '上饶': 'SRG', '怀化': 'HHQ',
            '大同': 'DTV', '银川': 'YIJ', '岳阳': 'YYQ', '沧州': 'COP', '齐齐哈尔': 'QHX', '佛山': 'FSQ', '广元': 'GYW', '安庆': 'AQH',
            '湛江': 'ZJZ', '包头': 'BTC', '曲阜': 'QFK', '邢台': 'XTP', '茂名': 'MDQ', '丹东': 'DUT', '湖州': 'VZH', '聊城': 'UCK',
            '淮南': 'HAH', '达州': 'RXW', '恩施': 'ESN', '玉林': 'YLZ', '乐山北': 'UTW', '乐山': 'IVW', '鞍山': 'AST', '宿州': 'OXH',
            '汉中': 'HOY', '贵港': 'GGZ', '日照': 'RZK', '泰州': 'UTH', '廊坊': 'LJP', '盐城': 'AFH', '衡水': 'HSP', '盘锦': 'PVD',
            '郴州': 'CZQ', '周口': 'ZKN', '常德': 'VGQ', '宝鸡': 'BJY', '连云港': 'UIH', '韶关': 'SNQ', '曲靖': 'QJM', '吉安': 'VAG',
            '十堰': 'SNN', '遂宁': 'NIW', '德阳': 'DYW', '莆田': 'PTS', '本溪': 'BXT', '滁州': 'CXH', '辽阳': 'LYT', '运城': 'YNV',
            '衢州': 'QEH', '中山': 'ZSQ', '葫芦岛': 'HLD', '温岭': 'VHH', '平顶山': 'PEN', '湘潭': 'XTQ', '牡丹江': 'MDB', '三门峡': 'SMF',
            '铜陵': 'TJH', '安顺': 'ASW', '马鞍山': 'MAH', '淮北': 'HRH', '漳州': 'ZUS', '都江堰': 'DDW', '四平': 'SPT', '咸阳': 'XYY',
            '萍乡': 'PXG', '丽水': 'USH', '鹤壁': 'HAF', '景德镇': 'JCG', '通辽': 'TLD', '邵阳': 'SYQ', '凯里': 'KLW', '天水': 'TSJ',
            '亳州': 'BZH', '永州': 'AOQ', '渭南': 'WNY', '丹阳': 'DYH', '淮安': 'AUH', '六盘水': 'UMW', '临汾': 'LFV', '池州': 'IYH',
            '孝感': 'XGN', '娄底': 'LDQ', '肇庆': 'ZVQ', '宜春': 'YEG', '大庆': 'DZX', '滕州': 'TXK', '鹰潭': 'YTG', '诸暨': 'ZDH',
            '内江': 'NJW', '延安': 'YWY', '阳江': 'WRQ', '黄石': 'HSN', '巢湖': 'CIH', '贺州': 'HXZ', '荆门': 'JMN', '宜兴': 'YUH',
            '潢川': 'KCN', '承德': 'CDP', '益阳': 'AEQ', '铜仁': 'RDQ', '莱阳': 'LYK', '峨眉山': 'IXW', '咸宁': 'XNN', '玉溪': 'AXM',
            '清远': 'QBQ', '营口': 'YKT', '随州': 'SZN', '安康': 'AKY', '松原': 'VYT', '集宁南': 'JAC', '赤峰': 'CID', '汕头': 'OTQ',
            '宣城': 'ECH', '楚雄': 'CUM', '百色': 'BIZ', '平遥': 'PYV', '鄂州': 'ECN', '江油': 'JFW', '阳朔': 'YCZ', '眉山': 'MSW',
            '潜江': 'QJN', '高密': 'GMK', '嘉峪关': 'JGJ', '伊宁': 'YMR', '华山': 'HSY', '抚州': 'FZG', '海城': 'HCT', '白城': 'BCT',
            '长治': 'CZF', '嘉善': 'JSH', '阆中': 'LZE', '新余': 'XUG', '龙岩': 'LYS', '榆林': 'ALY', '建水': 'JSM', '河源': 'VIQ',
            '盘州': 'PAE', '临海': 'UFH', '梧州': 'WZZ', '瑞安': 'RAH', '麻城': 'MCN', '全椒': 'INH', '宜宾': 'YBW', '广安': 'VJW',
            '婺源': 'WYG', '铁岭': 'TLT', '敦煌': 'DHJ', '顺德': 'ORQ', '张家口': 'ZMP', '忻州': 'XXV', '海安': 'HIH', '黄冈': 'KGN',
            '祥云': 'XQM', '临河': 'LHC', '巩义': 'GXF', '库尔勒': 'KLR', '兰考': 'LKF', '定州': 'DXP', '溧阳': 'LEH', '乐清': 'UPH',
            '永康': 'RFH', '晋城': 'JCF', '张掖': 'ZYJ', '汕尾': 'OGQ', '东营': 'DPK', '民权': 'MQF', '鄂尔多斯': 'EEC', '绥化': 'SHB',
            '苍南': 'CEH', '侯马': 'HMV', '福清': 'FQS', '揭阳南': 'JRQ', '钦州': 'QRZ', '长兴': 'CBH', '攀枝花': 'PRW', '梅州': 'MOQ',
            '石河子': 'SZR', '邹城': 'ZIK', '邳州': 'PJH', '霸州': 'RMP', '宁德': 'NES', '抚顺': 'FST', '邓州': 'DOF', '兴义': 'XRZ',
            '兴城': 'XCD', '平南南': 'PAZ', '无为': 'IIH', '武威': 'WUJ', '桂平': 'GAZ', '阳泉曲': 'YYV', '阳泉': 'AQP', '大石桥': 'DQT',
            '宁海': 'NHH', '利川': 'LCN', '高碑店': 'GBP', '南部': 'NBE', '平阳': 'ARH', '吴川': 'WAQ', '德清': 'DRH', '吕梁': 'LHV',
            '杨陵': 'YSY', '潮州': 'CKQ', '滨州': 'BIK', '濮阳': 'PYF', '砀山': 'DKH', '镇远': 'ZUW', '奎屯': 'KTR', '枣阳': 'ZYN',
            '隆昌': 'LCW', '来宾': 'UBZ', '涿州': 'ZXP', '武夷山北': 'WBS', '任丘': 'RQP', '宣威': 'XWM', '通化': 'THL', '通化县': 'TXL',
            '喀什': 'KSR', '酒泉': 'JQJ', '阿克苏': 'ASR', '哈密': 'HMR', '江山': 'JUH', '涡阳': 'GYH', '曹县': 'CXK', '中卫': 'ZWJ',
            '乌海': 'WVC', '资阳': 'ZYW', '安陆': 'ALN', '广汉': 'GHW', '辛集': 'ENP', '汝州': 'ROF', '涪陵': 'FLW', '汉川': 'HCN',
            '鸡西': 'JXB', '共青城': 'GAG', '东台': 'DBH', '丰城': 'FCG', '吐鲁番': 'TFR', '昭通': 'ZDW', '合浦': 'HVZ', '陇南': 'INJ',
            '平邑': 'PIK', '如皋': 'RBH', '云梦': 'YMN', '谷城': 'GCN', '上虞': 'BDH', '琼海': 'QYQ', '武陟': 'WIF', '赤壁': 'CBN',
            '瑞金': 'RJG', '费县': 'FXK', '敦化': 'DHL', '耒阳': 'LYQ', '龙游': 'LMH', '自贡': 'ZGW', '蒙自': 'MZM', '天门': 'TMN',
            '平果': 'PGZ', '福鼎': 'FES', '桐城': 'TTH', '灵宝': 'LBF', '高安': 'GCG', '钟祥': 'ZTN', '梅河口': 'MHL', '锡林浩特': 'XTC',
            '绥中': 'SZD', '定西': 'DSJ', '辽源': 'LYL', '克拉玛依': 'KHR', '营山': 'NUW', '镇平': 'ZPF', '济源': 'JYF', '公主岭': 'GLT',
            '草海': 'WBW', '陵水': 'LIQ', '肇东': 'ZDB', '白沟': 'FEP', '大荔': 'DNY', '长葛': 'CEF', '朔州': 'SUV', '苍溪': 'CXE',
            '洋县西': 'YXY', '从江': 'KNW', '巴中': 'IEW', '莱西': 'LXK', '平凉': 'PIJ', '明光': 'MGH', '开原': 'KYT', '醴陵': 'LLG',
            '樟树': 'ZSG', '满洲里': 'MLX', '绥德': 'ODY', '应城': 'YHN', '云霄': 'YBS', '太谷': 'TGV', '西平': 'XPN', '东方': 'UFQ',
            '岳池': 'AWW', '郓城': 'YPK', '大足南': 'FQW', '西峡': 'XIF', '万宁': 'WNQ', '霞浦': 'XOS', '原平': 'YPV', '永嘉': 'URH',
            '藤县': 'TAZ', '长寿': 'EFW', '福安': 'FAS', '唐河': 'THF', '德惠': 'DHT', '玉屏': 'YZW', '梁山': 'LMK', '新化': 'EHQ',
            '玉山': 'YNG', '昌乐': 'CLK', '南陵': 'LLH', '连江': 'LKS', '盖州': 'GXT', '英德': 'YDQ', '文昌': 'WEQ', '简阳': 'JYW',
            '渑池': 'MCF', '陆川': 'LKZ', '青田': 'QVH', '扶余': 'FYT', '于都': 'YDG', '固始': 'GXN', '六枝': 'LIW', '格尔木': 'GRO',
            '项城': 'ERN', '崇左': 'CZZ', '大英东': 'IAW', '泊头': 'BZP', '蕲春': 'QRN', '泾县': 'LOH', '兴宁': 'ENQ', '兴国': 'EUG',
            '广德': 'GRH', '阿尔山': 'ART', '鹤岗': 'HGB', '石林': 'SLM', '鲁山': 'LAF', '金昌': 'JCJ', '建始': 'JRN', '珲春': 'HUL',
            '汨罗': 'MLQ', '井冈山': 'JGG', '光山': 'GUN', '田阳': 'TRZ', '廉江': 'LJZ', '万源': 'WYY', '渠县': 'QRW', '惠安': 'HNS',
            '信丰': 'EFG', '武胜': 'WSE', '奉化': 'FHH', '商城': 'SWN', '蓬安': 'PAW', '晏城': 'YEK', '北安': 'BAB', '武义': 'RYH',
            '阳西': 'WMQ', '乳山': 'ROK', '禹城': 'YCK', '安达': 'ADX', '泰和': 'THG', '都昌': 'DCG', '汤阴': 'TYF', '梁平': 'UQW',
            '黑河': 'HJB', '太湖': 'TKH', '海阳北': 'HEK', '洪洞': 'HDV', '通海': 'TAM', '双鸭山': 'SSB', '漳浦': 'ZCS', '东乡': 'DXG',
            '固原': 'GUJ', '固镇': 'GEH', '肃宁': 'SYP', '湘乡': 'XXQ', '德安': 'DAG', '临清': 'UQK', '韩城': 'HCY', '永修': 'ACG',
            '漠河': 'MVX', '加格达奇': 'JGX', '萨拉齐': 'SLC', '商洛': 'OLY', '水家湖': 'SQH', '阿城': 'ACB', '和田': 'VTR', '博乐': 'BOR',
            '青县': 'QXP', '沂水': 'YUK', '瑞昌': 'RCG', '尚志': 'SZB', '牙克石': 'YKX', '阳春': 'YQQ', '新县': 'XSN', '怀仁': 'HRV',
            '罗山': 'LRN', '大方南': 'DNE', '伊春': 'YCB', '当阳': 'DYN', '白河': 'BEL', '彭山': 'PSW', '武穴': 'WXN', '蛟河': 'JHL',
            '兴业': 'SNZ', '北屯市': 'BXR', '台安': 'TID', '阿勒泰': 'AUR', '城固': 'CGY', '台前': 'TTK', '富源': 'FYM', '图们': 'TML',
            '靖西': 'JMZ', '高平': 'GPF', '汾阳': 'FAV', '内乡': 'NXF', '泰宁': 'TNS', '南召': 'NAF', '永泰': 'YTS', '道州': 'DFZ',
            '浠水': 'XZN', '宁国': 'NNH', '德令哈': 'DHO', '蒲城': 'PCY', '南靖': 'NJS', '甘谷': 'GGJ', '双辽': 'ZJD', '富锦': 'FIB',
            '修武': 'XWF', '慈利': 'CUQ', '罗平': 'LPM', '罗源': 'LVS', '溆浦': 'EPQ', '祁县': 'QXV', '灵石': 'LSV', '嫩江': 'NGX',
            '洋河': 'GTH', '广通北': 'GPM', '三水': 'SJQ', '平昌': 'PCE', '通渭': 'TWJ', '确山': 'QSN', '扶绥': 'FSZ', '织金': 'IZW',
            '南城': 'NDG', '临高南': 'KGQ', '鄯善': 'SSR', '乌拉特前旗': 'WQC', '巴东': 'BNN', '卫辉': 'WHF', '民和南': 'MNO', '海伦': 'HLB',
            '铁力': 'TLB', '阜宁': 'AKH', '东光': 'DGP', '长垣': 'CYF', '高州': 'GSQ', '焉耆': 'YSR', '临澧': 'LWQ', '博白': 'BBZ',
            '日喀则': 'RKO', '定边': 'DYJ', '沂南': 'YNK', '宁乡': 'NXQ', '青铜峡': 'QTJ', '彰武': 'ZWD', '临颍': 'LNF', '诏安': 'ZDS',
            '新干': 'EGG', '五常': 'WCB', '河津': 'HJV', '叶柏寿': 'YBD', '平原': 'PYK', '乐东': 'UQQ', '密山': 'MSB', '大安': 'RAT',
            '贵溪': 'GXG', '龙南': 'UNG', '信宜': 'EEQ', '尤溪': 'YXS', '徐闻': 'XJQ', '石嘴山': 'QQJ', '息县': 'ENN', '大板': 'DBC',
            '乐昌': 'LCQ', '阳高': 'YOV', '庆安': 'QAB', '芷江': 'ZPQ', '泗水': 'OSK', '师宗': 'SEM', '阳谷': 'YIK', '桐梓': 'TZW',
            '桐柏': 'TBF', '丰镇': 'FZC', '饶阳': 'RVP', '容县': 'RXZ', '宁武': 'NWV', '舒兰': 'SLL', '七台河': 'QTB', '凌海': 'JID',
            '郯城': 'TZK', '涟源': 'LAQ', '清原': 'QYT', '甘旗卡': 'GQD', '红安': 'HWN', '永福南': 'YBZ', '洮南': 'TVT', '米易': 'MMW',
            '襄汾': 'XFV', '林口': 'LKB', '磐石': 'PSL', '灯塔': 'DGT', '靖边': 'JIY', '海林': 'HRB', '贵定': 'GTW', '南雄': 'NCQ',
            '深州': 'OZP', '彭泽': 'PZG', '玉门': 'YXJ', '巴楚': 'BCR', '明港': 'MGN', '奈曼': 'NMD', '清河城': 'QYP', '那曲': 'NQO',
            '绥棱': 'SIB', '江华': 'JHZ', '岑溪': 'CNZ', '长汀': 'CES', '商都': 'SXC', '宝清': 'BUB', '四合永': 'OHD', '松滋': 'SIN',
            '麻阳': 'MVQ', '德保': 'RBZ', '通榆': 'KTT', '天义': 'TND', '隆化': 'UHP', '察素齐': 'CSC', '米脂': 'MEY', '正镶白旗': 'ZXC',
            '临湘': 'LXQ', '旬阳': 'XUY', '公营子': 'GYD', '莎车': 'SCR', '兴平': 'XPY', '化德': 'HGC', '乐都': 'LDO', '集安': 'JAL',
            '柳河': 'LNL', '宣汉': 'XHY', '镇赉': 'ZLT', '遂溪': 'SXZ', '雷州': 'UAQ', '中宁': 'VNJ', '富拉尔基': 'FRX', '义马': 'YMF',
            '霍邱': 'FBH', '彬州': 'BXY', '桑根达来': 'OGC', '资中': 'ZZW', '兴安': 'XAZ', '应县': 'YZV', '荣昌': 'RCW', '汤原': 'TYB',
            '东明县': 'DNF', '分宜': 'FYG', '鹿寨': 'LIZ', '中牟': 'ZGF', '西乡': 'XQY', '山丹': 'SDJ', '西丰': 'XFT', '林东': 'LRC',
            '定陶': 'DQK', '邵武': 'SWS', '兰溪': 'LWH', '依安': 'YAX', '托克托东': 'TVC', '北流': 'BOZ', '代县': 'DKV', '盐津': 'AEW',
            '横峰': 'HFG', '丰顺': 'FUQ', '博兴': 'BXK', '峡江': 'EJG', '安化': 'PKQ', '会昌北': 'XEG', '陇县': 'LXY', '轮台': 'LAR',
            '泗县': 'GPH', '甘洛': 'VOW', '德昌': 'DVW', '瓜州': 'GZJ', '水富': 'OTW', '新和': 'XIR', '勃利': 'BLB', '太平川': 'TIT',
            '繁峙': 'FSV', '歙县': 'OVH', '灵丘': 'LVV', '富县': 'FEY', '新晃': 'XLQ', '稷山': 'JVV', '阳信': 'YVK', '林西': 'LXC',
            '遂平': 'SON', '高台': 'GTJ', '融安': 'RAZ', '略阳': 'LYY', '枣强': 'ZVP', '宜城': 'YIN', '沁县': 'QVV', '安口窑': 'AYY',
            '涞源': 'LYP', '永安': 'YAS', '永安乡': 'YNB', '叶城': 'YER', '阎良': 'YNY', '福山镇': 'FZQ', '丹凤': 'DGY', '元谋': 'YMM',
            '获嘉': 'HJF', '卓资山': 'ZZC', '永定': 'YGS', '茶陵': 'CDG', '保康': 'BKD', '尼勒克': 'NIR', '泽普': 'ZPR', '安仁': 'ARG',
            '固安': 'GFP', '天祝': 'TZJ', '宁明': 'NMZ', '寿阳': 'SYV', '阿图什': 'ATR', '东丰': 'DIL', '平安驿': 'PNO', '松桃': 'MZQ',
            '同心': 'TXJ', '宁安': 'NAB', '孙吴': 'SKB', '襄垣': 'EIF', '福海': 'FHR', '蔡家崖': 'EBV', '涉县': 'OEP', '临泽': 'LEJ',
            '沁阳': 'QYF', '新兴县': 'XGQ', '武安': 'WAP', '施秉': 'AQW', '塔河': 'TXX', '凤县': 'FXY', '沙县': 'SAS', '白文东': 'BCV',
            '新安县': 'XAF', '穆棱': 'MLB', '澧县': 'LEQ', '平房': 'PFB', '新肇': 'XZT', '冕宁': 'UGW', '炎陵': 'YAG', '田东': 'TDZ',
            '资溪': 'ZXS', '光泽': 'GZS', '墨玉': 'MUR', '子洲': 'ZZY', '根河': 'GEX', '西林': 'XYB', '柞水': 'ZSY', '皮山': 'PSR',
            '勉县': 'MVY', '喜德': 'EDW', '南杂木': 'NZT', '银滩': 'CTQ', '临江': 'LQL', '仪征': 'UZH', '新乐': 'ELP', '扎鲁特': 'ZLD',
            '凤阳': 'FUH', '新绛': 'XJV', '安溪': 'AXS', '峨边': 'EBW', '田林': 'TFZ', '祁门': 'QIH', '余江': 'YHG', '安平': 'APT',
            '辰溪': 'CXQ', '顺昌': 'SCS', '兴和西': 'XEC', '和静': 'HJR', '抚松': 'FSL', '乾安': 'QOT', '三原': 'SAY', '罗城': 'VCZ',
            '天镇': 'TZV', '带岭': 'DLB', '神池': 'SMV', '钟山': 'ZSZ', '鄄城': 'JCK', '漳平': 'ZPS', '定襄': 'DXV', '阳城': 'YNF',
            '汝阳': 'RYF', '阿克陶': 'AER', '岢岚': 'KLV', '昂昂溪': 'AAX', '古田': 'GTS', '汤旺河': 'THB', '磁县': 'CIP', '英吉沙': 'YIR',
            '西固城': 'XUJ', '黎城': 'UCP', '双牌': 'SBZ', '张家川': 'ZIJ', '芦溪': 'LUG', '长武': 'CWY', '白音察干': 'BYC', '通道': 'TRQ',
            '册亨': 'CHZ', '上杭': 'JBS', '朱日和': 'ZRC', '闽清': 'MQS', '美溪': 'MEB', '盘山': 'PUD', '文安': 'WBP', '永寿': 'ASY',
            '汪清': 'WQL', '旺苍': 'WEW', '彝良': 'ALW', '澄城': 'CUY', '乌伊岭': 'WPB', '桃山': 'TAB', '安龙': 'AUZ', '大关': 'RGW',
            '弥渡': 'MDF', '新青': 'XQB', '红山': 'VSB', '四方台': 'STB', '马龙': 'MGM', '甘泉': 'GQY', '友好': 'YOB', '千阳': 'QOY',
            '长阳': 'CYN', '桐子林': 'TEW', '疏勒': 'SUR', '团结': 'TIX', '永乐店': 'YDY', '汤池': 'TCX', '海晏': 'HFO', '姚安': 'YAC',
            '衡南': 'HNG', '滴道': 'DDB', '乃林': 'NLD', '杨岗': 'YRB', '南木': 'NMX', '中和': 'ZHX', '麻山': 'MAB', '东津': 'DKB',
            '江边村': 'JBG', '小村': 'XEM', '石磷': 'SPB', '香港西九龙': 'XJA', '白山市': 'HJL', '白银市': 'BNJ', '朝阳镇': 'CZL',
            '杜尔伯特': 'TKX', '江门东': 'JWQ', '乐平市': 'LPG', '冷水江东': 'UDQ', '莱芜东': 'LWK', '南宫东': 'NFP', '宁陵县': 'NLF',
            '青州市': 'QZK', '双城北': 'SBB', '三河县': 'OXP', '三门县': 'OQH', '石门县': 'OMQ', '石泉县': 'SXY', '沙湾县': 'SXR',
            '仙桃西': 'XAN', '夏邑县': 'EJH', '虞城县': 'IXH', '枝江北': 'ZIN', '安江东': 'ADA', '北票': 'BPT', '朝阳': 'VBT',
            '东港北': 'RGT', '防城港北': 'FBZ', '繁昌西': 'PUH', '阜新': 'FOT', '句容西': 'JWH', '龙口市': 'UKK', '蓬莱市': 'POK',
            '三明': 'SVS', '乌苏': 'WSR', '萧县北': 'QSH', '雅安': 'YAE', '永城北': 'RGH', '云浮东': 'IXQ', '邹平': 'ZLK', '额敏': 'EMR',
            '北京大兴': 'IPP', '南平市': 'NOS'}
